services:
  - type: web
    name: snipp-sv
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ALLOWED_ORIGIN
        value: ""
      - key: PORT
        value: "3000"
    disk:
      name: texts
      mountPath: /opt/render/project/src/texts
      sizeGB: 1
